# Generated by Django 5.2.1 on 2025-05-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('due_date', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('report', models.CharField(max_length=200)),
                ('worked_hr', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='admin',
        ),
    ]
